### ISSUE TITLE
External-lb integration

### ISSUE THREAD

**Issue by hwinkel** [rancher/external-lb#1]
Nice to see the extarnal-lb keeps going. I'm wondering how the external-lb will be integrated in rancher, can a external-lb included in a stack like the internal-lb? or is it totally separate like the external-dns thing?

**Comment by deniseschannon** [comment]
@hwinkel I'm going to close the issues in this repo. Can you ask in rancher repo? We direct all issues into Rancher so that we can try to answer them.
